baseURL = "/"
languageCode = "en-us"
title = "Baltazar Ortega"
theme = "hello-friend"
paginate = 5

[params]
    defaultTheme = "light"
    showMenuItems = 2
    showReadingTime = false

    [menu]
        [[menu.main]]
            identifier = "about"
            name = "Sobre mi"
            url = "/about"
        [[menu.main]]
            identifier = "miscelanea"
            name = "Miscelanea"
            url = "/miscelanea"